[colors.normal]
black   = "#282828"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"

[colors.bright]
black   = "#928374"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"

[colors.special]
background = "#282828"
foreground = "#d4be98"
cursor     = "#d4be98"
